language: node_js
node_js:
- node
before-script:
- npm run build
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: Mup6tfiL2qOYnXdK3OIntf11qNfcT6GTxSMnqQNNA7ox5mREOZXIA/xCN0GGgRsQTRxUml3I/+xW0/kD1Ok8tdbRqb2l5KaZMlG8nIGWx+EvM3ukw4nUX8WWGBcXlIk0BFbU6xi/aQr6gZMDDmopVkxI2cJzanT0WZ8N7x/Q2tJvNWlxheJemjduXcqj212lvK92DIqX4Qm5SWRWf9pj6F2H8z2ngKjydGxmZZvl3zDVEwkssH13xWE+j9+c4uMj6iaPqJZ1ZgbL2YTyZxJOLq0znvVadBkoZ6yXBkWJAg9YzPhI/rx4DjWw1HJHRBTgF8Z+Rfeo5jlpuz+57uYev3x2hV708vOmVHwNxzFoSFfJJpZhGkJWImElWSuuIme3JroKUg48AGXMj0eOXKhiJvYSUMSnbHP8ro2WJ1DO7W2GQMpKn1gXhMM6iurKm+w6zva/bjmPxJx6qnYerBXf3+hLaphe+L7+mquCoMEyH2o725nGIs56Y8S9gZabvXGvvG5naRMt9GvYeOhChY+3COgHu3demMiyFV0fL1tfR4OwV8PvRifbua6JfmRi5uiPjG8Juyib6C1hJWvPv9LkKYdoIQMDEQzp4ovi/BvKaoP+R0zNiIY25siP7KS2vdPjjcLs6LentjQuZIcj59Wm3l0bUDBw75n0c5LG1zLxHL0=
  app: thawing-river-17731
